name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -name:printing greeting
       run:echo "helo world"
      -name:printing goodbye
       run:echo "goodbye world"
  
  
