name: Problem 004 Workflow
on:
  workflow_dispatch:
    inputs:
      database:
        description: 'Database name'
        required: true
        type: string
      backup_type:
        description: 'Backup type'
        required: true
        type: choice
        options:
          - full
          - incremental
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ github.event.inputs.database }}
      BACKUP_TYPE: ${{ github.event.inputs['backup-type']}}
    steps:
      - uses: actions/checkout@v4
      - name: Validate inputs
        run: |
          if [ -z "${{DB_NAME}}" ]; then
            echo "database name not provided"
            exit 1
          fi
 
  backup:
    needs: validate
    runs-on: ubuntu-latest
    needs: validate
    environment: production
    steps:
      - name: Perform backup 
        run: |
          echo "Starting $BACKUP_TYPE bckup for $DB_NAME"
          # Backup simulation
          sleep 30
          echo "Backup completed"

  notify:    
    runs-on: ubuntu-latest
    needs: backup
    if: always()
    steps:
      - name: Send notification
        run: echo "Backup process ${{ job.status }}"
